### PR TITLE
Add table only if it does not exists

### PR DESCRIPTION
**Pull request by BrainBuzzer**
This is a solution to issue #60 where teams migration was replicating itself. It's more safe than previous ones.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
:-1:

**Comment by GrahamCampbell** [comment]
This is not a good idea because of the down method. It makes no sense to say create if not created on up, and always remove on down. That behaviour is wrong.

**Comment by BrainBuzzer** [comment]
But this creates a table only if there is not one present already. Else, when I tested it out, it seemed like a bug. But even other's have the same problem so created a PR

**Comment by GrahamCampbell** [comment]
> But this creates a table only if there is not one present already.

Yes, that behaviour is WRONG, because the "down" method MUST reverse the migration, which means is MUST NOT remove the table if the up method didn't create it.

Do you see why this is wrong now?

**Comment by BrainBuzzer** [comment]
Yeah got it.

**Comment by BrainBuzzer** [comment]
But what would be soltion to this bug???

**Comment by GrahamCampbell** [comment]
It's not a bug? You shouldn't have a teams table already. If you do, you need to write yourself a custom migration that won't try to delete it on rollback.

**Pull request closed without merging**
