### PR TITLE
Add ownedTeams method to CanJoinTeams trait

### PR DESCRIPTION
**Pull request by mpociot**
This method could be useful if you want to restrict certain methods to the team owner.

### CODE REVIEW

**Comment by mikebronner** [comment]
I can see this being great for use in Policies :) :+1:

**Comment by taylorotwell** [comment]
I wonder if this should be a scope?

**Comment by srmklive** [comment]
perfect :+1:

**Comment by mpociot** [comment]
@taylorotwell hm..a scope on the Team model?
So something like:

```php
Team::ownedByMe()->get();
// or
Team::ownedBy($user)->get();
```

I like that :)

Maybe we should do both?

**Comment by CoderFetch** [comment]
:+1: Great idea!

**Comment by srmklive** [comment]
@mpociot I think doing both will be great. But i would suggest using only the **ownedBy** method as a scope. If no parameter is passed, it will get the current logged in user.

**Comment by fwartner** [comment]
I agree with @srmklive

**Comment by CoderFetch** [comment]
@srmklive :+1: Agreed.

**Pull request merged**
