### PR TITLE
Moved controllers and routes into userland on install to allow to easy extension/modification

### PR DESCRIPTION
**Pull request by Lidbetter**
- Removed baseController and added the single trait to those classes which extended instead
- Removed automagic routes, added them instead to routes.php
- Added Controller stubs (published on install) to bring Spark Controllers into userland (and allow routes to work from routes.php
- Updated the installer to copy the controllers stubs into userland

=
My usecase for easily adjusting the routes/controllers is for Oauth login - now that routing and controllers live in userland it is very easy to change the url or just the controller login methods to support this.

Extending the Spark controllers into userland controllers allows for simple straightforward customisation for a the framework user. I cannot see any significant drawbacks in terms of applying fixes/updates to Spark (internal flexibility for changes etc.).

I think there is significant advantage to publishing routes where a framework user typically expects them to be, and avoids that 'automagic' feeling.

### CODE REVIEW

**Comment by riev** [comment]
I'm also hoping for more control over routes and the controller methods, but I would rather only have what I need to customise in my App directory. That way if I only customise a few methods and Taylor adds some new functionality in the original method, I can easily update them.

I would prefer a way for Laravel to be able to register the Spark routes before the App routes, so that the App routes can override them if needed. Another way could be to stop the App routes from being overridden.

Also it would be nice to have the Spark controllers be near enough empty and using a trait for the methods, which we can then use in our own controller and override if needed.

But it's brand new and still in beta, so I'm guessing more control and flexibility will come over time.

**Comment by jbrooksuk** [comment]
A config file to determine if routes should be registered or not would be cool.

**Comment by taylorotwell** [comment]
Yeah I'm not sure this is really the approach we want to do. Ideally I think you would wan to extend these controllers, and then point the IoC container to your extended instance so that yours get's instantiated. That way you don't have to worry about a bunch of methods you aren't customizing.

**Comment by Lidbetter** [comment]
@taylorotwell that seems sensible and really I am in favor of any solution which would allow for similar levels of customizability as this did (URI's, single methods, entire controller swaps), this approach was (perhaps naively) a simple way to get that done.

**Pull request closed without merging**
