### PR TITLE
Add some join/leave Team events

### PR DESCRIPTION
**Pull request by tobz-nz**
Added events for:

- user accept invitation
- usr joined a team
- user left a team
- user was removed from a team

### CODE REVIEW

**Comment by jeffreydevreede** [comment]
Just curious, what is the reason you use `\Illuminate\Contracts\Auth\Authenticatable` for the `RemovedFromTeam` event instead of using `\Illuminate\Contracts\Auth\Access\Authorizable` like you did with the other events?

Also I noticed you wrote `acceptTeamInvitation` in the invitation controller (instead of `AcceptTeamInvitation`), and on that note it be in past tense aswell? `AcceptedTeamInvitation`

**Comment by tobz-nz** [comment]
Because inconsistency? ;)

I've sorted out both your comments. The first was an incorrect type hint, and the second was just not well named - thanks for pointing it out.

**Comment by taylorotwell** [comment]
Is there a big reason for having two seperate events for "accepted team invitation" and "joined team"? They seem like the same thing?

**Comment by tobz-nz** [comment]
It was for some case where someone may want to do something specific for joining via invite and not on any other way of joining a team. I realise that out of the box there is only one way to join a team, but other ways could easily be built for specific projects.

I felt the separation could be useful.

**Pull request merged**
