### PR TITLE
User Address feature for Spark

### PR DESCRIPTION
**Pull request by srmklive**
# Summary
This PR adds feature to allow users to add their billing address information to Spark.

# Changes
## Configuration
Added configuration file to enable/disable address feature. Credit to @mpociot  @aaranmcguire for this suggestion.

## Database
This PR adds the following models to the Spark installation along with their relevant migrations:
* Country
* State
* Address

Furthermore following seed have been added as well:
* CountryTableSeeder
* StatesTableSeeder (has states data for US & Canada)

## Controllers
* Added **API\StatesController** to get associated states for a selected country.

#### Without Address (Spark Default)
laravel_-_2015-11-02_16 03 03

#### With Address Enabled
laravel_-_2015-11-02_16 04 59

### Without Address (Spark Default)
laravel_-_2015-11-02_16 18 03

### With Address Enabled
laravel_-_2015-11-26_17 23 30

### CODE REVIEW

**Comment by mpociot** [comment]
I really think this feature needs to be configurable.

There could be a lot of (US) SaaS products that simply don't want their users to enter all this information in the registration process.

**Comment by mikebronner** [comment]
Also (not knocking it) the form should be laid out the same as the other forms:
- right-aligned labels
- propper gaps between fields

(I'm guessing bootstrap is not applied correctly.)

Looks like a very useful feature! :)

**Comment by srmklive** [comment]
@mpociot i think you are right. But the behavior can be configured through code itself by publishing the spark views, and changing it accordingly.

**Comment by mpociot** [comment]
And maybe you should change the name of the AddressBook model to "BillingAddress".
Because that's what it is. It's not a book, it contains only one address.

**Comment by mpociot** [comment]
@srmklive yes, but you can't modify the AuthController validation by publishing the views.

**Comment by srmklive** [comment]
@mpociot :thanks for the suggestion :). Will implement that definitely :+1:

**Comment by aaranmcguire** [comment]
I don't like that the users Billing Address is asked for "No Subscription" & "Free Subscription".. and in practice that could reduce signups (Even for paid subscriptions). 

It's not something Forge or Envoyer do.

**Comment by mikebronner** [comment]
@aaranmcguire  Agreed, should be togglable.

**Comment by srmklive** [comment]
@aaranmcguire I agree on this. @mpociot has already pointed it out. I will look to implement it as soon as possible.

**Comment by aaranmcguire** [comment]
@srmklive #97 Has it for paid plans only, so may be worth looking at how that was done.

**Comment by srmklive** [comment]
@taylorotwell whats your view on this PR?

**Comment by kayyyy** [comment]
@taylorotwell any thoughts an this PR? :)

**Comment by kayyyy** [comment]
Is there any thought from you @taylorotwell  ? :)

**Comment by taylorotwell** [comment]
Yeah I'm working towards this direction. I'll get there soon.

**Comment by kayyyy** [comment]
@taylorotwell you`re awesome +1

**Comment by taylorotwell** [comment]
I plan to do this but will implement it slightly differently.

**Comment by srmklive** [comment]
@taylorotwell Do you mean to put the address details inside the users table?

**Pull request closed without merging**
