### PR TITLE
Remove spaces from phone numbers

### PR DESCRIPTION
**Pull request by iBourgeois**
Remove any spaces from phone numbers

### CODE REVIEW

**Comment by phroggyy** [comment]
Might wanna replace any starting `+` with `00` while you're at it, to ensure a uniform formatting for all numbers.

**Comment by cwt137** [comment]
Might want to get rid of open and closed parentheses as well.

**Comment by iBourgeois** [comment]
You got it...

**Comment by iBourgeois** [comment]
@phroggyy Exit codes (00, 011, 99, etc...) are not be needed in this case. They are only used to MAKE an international call. In this case we are only RECEIVING an international text. Therefore the exit code should be generated by Twilio depending on where they send the text message from. 

Providing an exit code in your number will cause your request to fail!

**Pull request merged**
