### PR TITLE
Dot files

### PR DESCRIPTION
**Pull request by lucasmichot**
- Add a .editorconfig file
- Add a .gitattributes file
- Add a .php_cs file (taken from laravel/framework)
- Fix php files

### CODE REVIEW

**Comment by BrainBuzzer** [comment]
First 3 file commits are okay. But last commit should not be merged. These are not CS fixes. So I dont think so there is any need to merge last commit.

**Comment by lucasmichot** [comment]
@BrainBuzzer these ARE code style fixes
This is the result of `php-cs-fixer fix` against the definition file provided in https://github.com/lucasmichot/spark/commit/e1f7e30de6032bd11e522b5534a8d02ea7b6189b
Or maybe I don't follow you ?

**Comment by aaranmcguire** [comment]
@lucasmichot basicly create another pull request for the last commit.

**Comment by lucasmichot** [comment]
I would not make another PR as the file used for this fix is into this PR
it's a fixer file, please refer to issues history on http://github.com/laravel/framework

**Pull request merged**
