### PR TITLE
Fix #142

### LINKED ISSUE #142: Spark install
Hi, in the app/Console/Install.php file @ line 177, the script tries to copy:
```
SPARK_PATH.'/resources/stubs/database/migrations/2014_10_12_100000_create_subscriptions_tables.php'
```

But the migration file name should be  - (no **"s"**):
```
SPARK_PATH.'/resources/stubs/database/migrations/2014_10_12_100000_create_subscriptions_table.php'
```

### PR DESCRIPTION
**Pull request by dustinleblanc**

### CODE REVIEW

**Comment by taylorotwell** [comment]
This is correct because it creates multiple tables.

**Comment by dustinleblanc** [comment]
@taylorotwell okay, It looks like the issue is not plurality, it is that the install command is not using the migration as named. Should we tweak the migration then rather than the install command? This issue caused `spark install` to error out and quickly changing this line to match the actual migration got it up and running again.

**Comment by aaranmcguire** [comment]
@dustinleblanc What error are you seeing?

**Comment by dustinleblanc** [comment]
@aaranmcguire see #142

**Comment by aaranmcguire** [comment]
I seen that, but your only saying what you think should be changed, not what the error is. Looking at your commit, it would actually break the installer as your not renaming the file, only what the installer is pointing to. 

Also, like Talor mentioned, its not a bug/issue, its meant to be plural as there are multiple actions in the migration.

If you show the error message to mentioned that happens when you do `spark install` someone will be able to understand what your trying to do. (and maybe fix the issue).

**Comment by dustinleblanc** [comment]
@aaranmcguire the error is
```
[ErrorException]                                                                                                                                                                                    
  copy(/Users/dustin/code/php/estimaton/vendor/laravel/spark/resources/stubs/database/migrations/2014_10_12_100000_create_subscriptions_tables.php): failed to open stream: No such file or director  
  y
```
This happens on spark install. The reason is that the migration name is not consistent with the install command. The migration name is singular, the reference to it is plural. The plurality sounds fine to me and I understand the semantics. They just need to match for the installer to run. This fix worked to get the installer to finish. I think because of the lack of explanation from me (and I know better, shame on me) both of you have misinterpretted the PR. It is a bug, but perhaps just slightly different than my diff can show on it's own.

Back to my question, since they should be plural, shall I simply go rename the migration instead and resubmit? Again the only issue is inconsistency; which side it gets fixed on doesn't matter to me, I just wanted to make it so the installer runs and folks don't give up because they don't know why.

**Pull request closed without merging**
