### PR TITLE
Fire event on successful login attempt

### PR DESCRIPTION
**Pull request by aaranmcguire**
Adds the ability to listen to successful logins. May be useful for security and for user onboarding.

Note: Not tested yet but I can't see why this would not work.

### CODE REVIEW

**Comment by aaranmcguire** [comment]
Tested, Working.

**Comment by cwt137** [comment]
Hmm. I would like to see this done in the regular framework instead of Spark. Also, a login failure should trigger an event.

**Comment by aaranmcguire** [comment]
Looking on what the best way to trigger a login failure.

**Comment by aaranmcguire** [comment]
Just looked in the Laravel Framework. It seems this already exists, it's just not advertised. and its not using classes at the fire 'name'.

`auth.attempt`
`auth.login`
`auth.logout`

**Pull request closed without merging**
