### PR TITLE
Add referential itegrity to migrations

### PR DESCRIPTION
**Pull request by mikebronner**

### CODE REVIEW

**Comment by adamgoose** [comment]
Can I recommend adding the `onUpdate('cascade')` call as well?

**Comment by adamgoose** [comment]
Also, I've had luck with reversing migrations with foreign keys without actually dropping the foreign keys *if* you drop the tables in the *opposite* order as they were created.

**Comment by mikebronner** [comment]
@adamgoose thanks for your feedback, so updated ;-)
@taylorotwell Would you prefer the FKs in a separate migration file, or inline with the existing ones?

**Comment by taylorotwell** [comment]
Going to let the developer opt-in to this.

**Pull request closed without merging**
