### PR TITLE
Form Components and Customised Default Tabs

### PR DESCRIPTION
**Pull request by michaelrtm**
**Form Components**
Added Textfield Component with a Prop for rows - defaulting to 5
Modified Select to be 6 columns wide, not 8

**Customised Default Tabs**
I had need to change the text from 'Membership' on the Teams page, so I figured others may too.
There may also be need for people to use a different word besides 'Team' in their menu. I realise Team appears in the views, but most of that is controlled through views.

Perhaps later down the line in the configuration how 'Teams' is displayed could be an option that one sets?

### CODE REVIEW

**Comment by taylorotwell** [comment]
How come you defined the textarea component but never used it?

**Comment by michaelrtm** [comment]
I used it on a custom template off the teams tab.
I thought others may be in need of one in the admin panels

**Comment by taylorotwell** [comment]
I would be open to this without the textarea component addition.

**Comment by michaelrtm** [comment]
No problems. Were you open to the idea of a setting to rename teams?

**Pull request closed without merging**
